/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.*;
import dao.PaintBulletDaoImp;
import dto.PaintBulletDto;
import OurStack.Noded.Stackoon;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;

/**
 *
 * @author adoha
 */
public class PaintedView extends javax.swing.JFrame {
    private static PaintBulletDaoImp bulletManager;
    private static Stackoon paintBullets;
    
    private boolean isCharged;
    private boolean order;
    /**
     * Creates new form PaintedView
     */
    public PaintedView() {
        initComponents();
        customInit();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCargadorE = new javax.swing.JLabel();
        lblPistolaE = new javax.swing.JLabel();
        btnColocarCargador = new javax.swing.JButton();
        pnlCharger = new javax.swing.JPanel();
        lblCharger = new javax.swing.JLabel();
        lblMechanism = new javax.swing.JLabel();
        pnlCharger1 = new javax.swing.JPanel();
        lblCharged = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnTrigger = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlCargador = new javax.swing.JPanel();
        btn354e9e = new javax.swing.JButton();
        btn359e75 = new javax.swing.JButton();
        btn959e35 = new javax.swing.JButton();
        btn78359e = new javax.swing.JButton();
        btn9e6e35 = new javax.swing.JButton();
        btn9e3582 = new javax.swing.JButton();
        btn9e3544 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnMinimo = new javax.swing.JButton();
        btnMaximo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCambiar = new javax.swing.JButton();
        btnSortear = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnExterior = new javax.swing.JButton();
        btnInterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 300));
        setPreferredSize(new java.awt.Dimension(975, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCargadorE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cargador_exterior.png"))); // NOI18N
        getContentPane().add(lblCargadorE, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 23, 500, -1));

        lblPistolaE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pistola_exterior_b.png"))); // NOI18N
        getContentPane().add(lblPistolaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 93, 520, -1));

        btnColocarCargador.setText("Colocar Cargador");
        btnColocarCargador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColocarCargadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnColocarCargador, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, -1));

        pnlCharger.setOpaque(false);
        getContentPane().add(pnlCharger, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 280, 40));

        lblCharger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cargador.png"))); // NOI18N
        getContentPane().add(lblCharger, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 462, 350, -1));

        lblMechanism.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mecanismo_b.png"))); // NOI18N
        lblMechanism.setToolTipText("");
        getContentPane().add(lblMechanism, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 130, 460, 90));

        pnlCharger1.setOpaque(false);
        getContentPane().add(pnlCharger1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 280, 40));

        lblCharged.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cargador.png"))); // NOI18N
        getContentPane().add(lblCharged, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 49, 410, 120));

        btnTrigger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gatillo_b.png"))); // NOI18N
        btnTrigger.setBorderPainted(false);
        btnTrigger.setContentAreaFilled(false);
        btnTrigger.setFocusPainted(false);
        btnTrigger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriggerActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(btnTrigger, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnTrigger, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(btnTrigger, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 210, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pistola_interior.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 540, -1));

        pnlCargador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCargador.setOpaque(false);
        pnlCargador.setPreferredSize(new java.awt.Dimension(876, 150));

        btn354e9e.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bala_354e9e.png"))); // NOI18N
        btn354e9e.setName("btn354e9e"); // NOI18N
        btn354e9e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn354e9eActionPerformed(evt);
            }
        });

        btn359e75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bala_359e75.png"))); // NOI18N
        btn359e75.setName("btn359e75"); // NOI18N
        btn359e75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn359e75ActionPerformed(evt);
            }
        });

        btn959e35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bala_959e35.png"))); // NOI18N
        btn959e35.setName("btn959e35"); // NOI18N
        btn959e35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn959e35ActionPerformed(evt);
            }
        });

        btn78359e.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bala_78359e.png"))); // NOI18N
        btn78359e.setName("btn78359e"); // NOI18N
        btn78359e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn78359eActionPerformed(evt);
            }
        });

        btn9e6e35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bala_9e6e35.png"))); // NOI18N
        btn9e6e35.setName("btn9e6e35"); // NOI18N
        btn9e6e35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9e6e35ActionPerformed(evt);
            }
        });

        btn9e3582.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bala_9e3582.png"))); // NOI18N
        btn9e3582.setName("btn9e3582"); // NOI18N
        btn9e3582.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9e3582ActionPerformed(evt);
            }
        });

        btn9e3544.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bala_9e3544.png"))); // NOI18N
        btn9e3544.setName("btn9e3544"); // NOI18N
        btn9e3544.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9e3544ActionPerformed(evt);
            }
        });

        jLabel2.setText("Clickear en los colores a cargar en el orden deseado");

        btnMinimo.setText("Buscar Mínimo");
        btnMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimoActionPerformed(evt);
            }
        });

        btnMaximo.setText("Buscar Máximo");
        btnMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Por Valor");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCambiar.setText("Cambiar Balas");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        btnSortear.setText("Sortear ID");
        btnSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCargadorLayout = new javax.swing.GroupLayout(pnlCargador);
        pnlCargador.setLayout(pnlCargadorLayout);
        pnlCargadorLayout.setHorizontalGroup(
            pnlCargadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCargadorLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(pnlCargadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCargadorLayout.createSequentialGroup()
                        .addComponent(btn354e9e, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn959e35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn359e75, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn78359e, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn9e6e35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn9e3582, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn9e3544, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCargadorLayout.createSequentialGroup()
                        .addComponent(btnMinimo)
                        .addGap(2, 2, 2)
                        .addComponent(btnMaximo)
                        .addGap(2, 2, 2)
                        .addComponent(btnEliminar)
                        .addGap(2, 2, 2)
                        .addComponent(btnCambiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSortear)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)))
                .addGap(28, 28, 28))
        );
        pnlCargadorLayout.setVerticalGroup(
            pnlCargadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCargadorLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlCargadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn9e3544)
                    .addComponent(btn9e3582)
                    .addComponent(btn9e6e35)
                    .addComponent(btn78359e)
                    .addComponent(btn359e75)
                    .addComponent(btn959e35)
                    .addComponent(btn354e9e))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(pnlCargadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinimo)
                    .addComponent(btnMaximo)
                    .addComponent(btnEliminar)
                    .addComponent(btnCambiar)
                    .addComponent(btnSortear)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20))
        );

        getContentPane().add(pnlCargador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 890, 190));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 120, -1));

        btnCreditos.setText("Créditos");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 80, -1));

        btnExterior.setText("Exterior");
        btnExterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnExterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        btnInterior.setText("Interior");
        btnInterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnInterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTriggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriggerActionPerformed
        // Función botón gatillo
        // Elimina el tope de la pila y realiza "animaciones" de la bala disparandose
        
        
        btnTrigger.setIcon(new ImageIcon(getClass().getResource("/image/gatillo_a.png")));
        lblMechanism.setIcon(new ImageIcon(getClass().getResource("/image/mecanismo_a.png")));
        Component compAux;
        if(isCharged) {
            if(!paintBullets.isVoid()) {
                for (Component component : pnlCharger1.getComponents()) {
                    String name = component.getName();
                    System.out.println(name);
                    String color = ((PaintBulletDto)paintBullets.getFirst().getValor()).getColor();
                    System.out.println(color);
                    
                    // TimeTask para atrasar cambio de posiciones. "animación"
                    if(name.substring(3,name.length()).equals(color)) {
                        compAux = component;
                        try {
                            getContentPane().add(component,3);
                        } catch(Exception e){}
                        component.setLocation(235,152);
                        int loc = 235;
                        for (int i = 0; i < 10; i++) {
                            new java.util.Timer().schedule( 
                                new java.util.TimerTask() {
                                    @Override
                                    public void run() {
                                        component.setLocation(component.getLocation().x + 40,152);
                                    }
                                }, 
                                50 
                            );
                        }
                      new java.util.Timer().schedule( 
                        new java.util.TimerTask() {
                        @Override
                        public void run() {getContentPane().remove(component);}}, 100);   
                      getContentPane().revalidate();
                      getContentPane().repaint();
                    }     
                }
                                      getContentPane().setBackground(Color.decode("#"+ ((PaintBulletDto)paintBullets.getFirst().getValor()).getColor()));

                paintBullets.dropFirst();
                displayBullets(pnlCharger1);
                            } else {
                JOptionPane.showMessageDialog(null, "No hay balas cargadas!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay cargador puesto!");
        }
        new java.util.Timer().schedule( 
            new java.util.TimerTask() {
            @Override
            public void run() {
                btnTrigger.setIcon(new ImageIcon(getClass().getResource("/image/gatillo_b.png")));
                lblMechanism.setIcon(new ImageIcon(getClass().getResource("/image/mecanismo_b.png"))); 
            }},100);
    }//GEN-LAST:event_btnTriggerActionPerformed

    private void btn354e9eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn354e9eActionPerformed
        chargeBullet(evt);  
    }//GEN-LAST:event_btn354e9eActionPerformed

    private void btn959e35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn959e35ActionPerformed
        chargeBullet(evt); 
    }//GEN-LAST:event_btn959e35ActionPerformed

    private void btn359e75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn359e75ActionPerformed
        chargeBullet(evt); 
    }//GEN-LAST:event_btn359e75ActionPerformed

    private void btn78359eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn78359eActionPerformed
        chargeBullet(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_btn78359eActionPerformed

    private void btn9e6e35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9e6e35ActionPerformed
        chargeBullet(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_btn9e6e35ActionPerformed

    private void btn9e3582ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9e3582ActionPerformed
        chargeBullet(evt);       // TODO add your handling code here:
    }//GEN-LAST:event_btn9e3582ActionPerformed

    private void btn9e3544ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9e3544ActionPerformed
        chargeBullet(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_btn9e3544ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnColocarCargadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColocarCargadorActionPerformed
        //Coloca cargador y maneja visuales de este
        
        if(!isCharged){
            setPreferredSize(new Dimension(975, 500));
            setSize(new Dimension(975, 500));
            pnlCargador.setVisible(false);
            lblCharged.setVisible(true);
            lblCharger.setVisible(false);
            pnlCharger.setVisible(false);
            displayBullets(pnlCharger1);
            isCharged = true; 
            lblPistolaE.setVisible(false);
            lblCargadorE.setVisible(false);
            pack();
        }
        //getContentPane().repaint();
    }//GEN-LAST:event_btnColocarCargadorActionPerformed

    private void btnMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimoActionPerformed
        try {
            JOptionPane.showMessageDialog(null, "Bala con ID: " + bulletManager.getMin().getId(), "Elemento Mínimo", HEIGHT, new ImageIcon(getClass().getResource("/image/bala_" + bulletManager.getMin().getColor() + ".png")));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnMinimoActionPerformed

    private void btnMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximoActionPerformed
        try {
            JOptionPane.showMessageDialog(null, "Bala con ID: " + bulletManager.getMax().getId(), "Elemento Máximo", HEIGHT, new ImageIcon(getClass().getResource("/image/bala_" + bulletManager.getMax().getColor() + ".png")));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnMaximoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int id = 0;
        do{
            String valor = "";     
            valor = JOptionPane.showInputDialog(null,"Ingrese la ID de la bala que desea eliminar:");
            if(valor == null || valor.trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Valor no puede estar vacío.");
                return;
            }else {
                try {
                    id = Integer.parseInt(valor.trim());
                    for (int i = 0; i < paintBullets.getSize(); i++) {
                        if(id == ((PaintBulletDto)paintBullets.GetByIndex(i)).getId()) {
                            if(paintBullets.DeleteByIndex(i)) {
                                displayBullets(pnlCharger);
                                getContentPane().repaint();
                                return;
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(null, "Una bala con esa ID no existe.");
                } catch(Exception e) {
                    JOptionPane.showMessageDialog(null, e.getStackTrace());
                    return;
                }
                break;
            }
        } while(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        int id1 = 0;
        int id2 = 0;
        boolean encontrado = false;
        do{
            String valor = "";     
            valor = JOptionPane.showInputDialog(null,"Ingrese el 1er ID para cambiar:");
            if(valor == null || valor.trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Valor no puede estar vacío.");
                return;
            }else {
                try {
                    id1 = Integer.parseInt(valor.trim());
                    for (int i = 0; i < paintBullets.getSize(); i++) {
                        if(id1 == ((PaintBulletDto)paintBullets.GetByIndex(i)).getId()) {
                           encontrado = true;
                        }
                    }
                    if(encontrado){
                        break;
                    }
                    JOptionPane.showMessageDialog(null, "Una bala con esa ID no existe.");
                } catch(Exception e) {
                    JOptionPane.showMessageDialog(null, e.getStackTrace());
                    return;
                }
                break;
            }
        } while(true);
        encontrado = false;
        do{
            String valor = "";     
            valor = JOptionPane.showInputDialog(null,"Ingrese el 1er 2D para cambiar:");
            if(valor == null || valor.trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Valor no puede estar vacío.");
                return;
            }else {
                try {
                    id2 = Integer.parseInt(valor.trim());
                    for (int i = 0; i < paintBullets.getSize(); i++) {
                        if(id2 == ((PaintBulletDto)paintBullets.GetByIndex(i)).getId()) {
                           encontrado = true;
                        }
                    }
                    if(encontrado){
                        break;
                    }
                    JOptionPane.showMessageDialog(null, "Una bala con esa ID no existe.");
                } catch(Exception e) {
                    JOptionPane.showMessageDialog(null, e.getStackTrace());
                    return;
                }
                break;
            }
        } while(true);
        if(id1 != 0 && id2!= 0){
            bulletManager.switchNodeId(id1, id2);
            displayBullets(pnlCharger);
            getContentPane().repaint();
        }
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortearActionPerformed
        
        if (order)
            order = false;
        else
            order = true;
        
        if (order)
            bulletManager.SortById(0);
        else 
            bulletManager.SortById(1);
        displayBullets(pnlCharger);
        getContentPane().revalidate();
    }//GEN-LAST:event_btnSortearActionPerformed

    private void btnInteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteriorActionPerformed
        lblPistolaE.setVisible(false);
        lblCargadorE.setVisible(false);
    }//GEN-LAST:event_btnInteriorActionPerformed

    private void btnExteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExteriorActionPerformed
        lblPistolaE.setVisible(true);
        if(isCharged)
            lblCargadorE.setVisible(true);
    }//GEN-LAST:event_btnExteriorActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        JOptionPane.showMessageDialog(null,
                "Realizado por:\n\n- Adolfo Astudillo Del Río\n- Sebastián Muñoz Vergara\n"
                + "----------------------------------------------\n"
                + "Gracias a:\n\n"
                + "- Artwork por Mikoto-Tsuki (Hermana de Sebastián)\n\n"
                + "- Nuestras ojeras, asistencia perdida (por sueño) y los mechones de pelo\n"
                + "----------------------------------------------\n"
                + "Realizado para:\n\n"
                + "- Clase Diseño de Estructuras de Datos\n"
                + "- Sección 2\n"
                + "- Profesor Juan Cubillos\n"
                + "- Carrera Analista Programador Computacional\n"
                + "- Duoc UC, Sede Padre Alonso de Ovalle 2017"
                );
    }//GEN-LAST:event_btnCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaintedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaintedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaintedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaintedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaintedView().setVisible(true);
            }
        });
    }
    
    public void chargeBullet(java.awt.event.ActionEvent evt) {
        // Agrega "balas" a la pila que son mostradas en el cargador
        
        PaintBulletDto paintBullet = new PaintBulletDto();
        String name = ((JButton)evt.getSource()).getName();
        System.out.println(name);
        String color = name.substring(3, name.length());
        System.out.println(color);
        paintBullet.setColor(color);
        int id = 0;
        do{
            String valor = "";     
            valor = JOptionPane.showInputDialog(null,"Ingrese valor con que asociar a la bala:");
            if(valor == null || valor.trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Valor no puede estar vacío.");
                return;
            }else {
                try {
                    id = Integer.parseInt(valor.trim());
                    for (int i = 0; i < paintBullets.getSize(); i++) {
                        if(id == ((PaintBulletDto)paintBullets.GetByIndex(i)).getId()) {
                            JOptionPane.showMessageDialog(null, "El valor ya existe. Se debe elegir otro.");
                            return;
                        }
                    }
                } catch(Exception e) {
                    JOptionPane.showMessageDialog(null, "Valor debe ser un número.");
                    return;
                }
                break;
            }
        } while(true);
        paintBullet.setId(id);
        paintBullets.pileUp(paintBullet);
        
        pnlCargador.remove((JButton)evt.getSource());
        
        displayBullets(pnlCharger);
        getContentPane().repaint();

        if(paintBullets.getSize() == 7) {
            
        }
        
        
        //pnlCargador.repaint();
    }
    
    public void displayBullets(JPanel pane){
        // Añade los componentes UI al panel del cargador. Muestra las balas
        pane.removeAll();
        pane.revalidate();
        for (int i = 0; i < paintBullets.getSize(); i++) {
            JLabel label = new JLabel(new ImageIcon(getClass().getResource("/image/bala_" + ((PaintBulletDto)paintBullets.GetByIndex(i)).getColor() + ".png")));
            label.setName("lbl" + ((PaintBulletDto)paintBullets.GetByIndex(i)).getColor());
            label.setPreferredSize(new Dimension(32,32));
            pane.add(label);
        }
        
    }
    
    public void customInit() {
        //Inicializador, se usa para reset()
        
        lblCargadorE.setVisible(false);
        lblCharged.setVisible(false);
        bulletManager = new PaintBulletDaoImp();
        paintBullets = bulletManager.bulletStack;
        pnlCharger.setLayout(new FlowLayout(FlowLayout.LEFT));
        pnlCharger1.setLayout(new FlowLayout(FlowLayout.LEFT));
    }
    
    public void reset() {
        // custom reset de la ventana
        
        getContentPane().setBackground(new Color(240,240,240));
        getContentPane().removeAll();
        initComponents();
        customInit();
        getContentPane().revalidate();
        getContentPane().repaint();
        isCharged = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn354e9e;
    private javax.swing.JButton btn359e75;
    private javax.swing.JButton btn78359e;
    private javax.swing.JButton btn959e35;
    private javax.swing.JButton btn9e3544;
    private javax.swing.JButton btn9e3582;
    private javax.swing.JButton btn9e6e35;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnColocarCargador;
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExterior;
    private javax.swing.JButton btnInterior;
    private javax.swing.JButton btnMaximo;
    private javax.swing.JButton btnMinimo;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSortear;
    private javax.swing.JButton btnTrigger;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblCargadorE;
    private javax.swing.JLabel lblCharged;
    private javax.swing.JLabel lblCharger;
    private javax.swing.JLabel lblMechanism;
    private javax.swing.JLabel lblPistolaE;
    private javax.swing.JPanel pnlCargador;
    private javax.swing.JPanel pnlCharger;
    private javax.swing.JPanel pnlCharger1;
    // End of variables declaration//GEN-END:variables
}
